### ISSUE TITLE
F01 修正

### ISSUE THREAD

**Issue by troyeagle** [troyeagle/drafts#2]
- [x] oblivious: we go further in the destiny 这句的K子重新扒一下
- [x] 你将化作光芒，「綺麗な空に」的そら写成そば了
- [x] 以及最后一个高潮前的大妈语最后一个和弦，求确认是74+还是1+4+还是71+4+
- [x] ARIA31小节きみをなくし「た」みらい
- [x] 40小节がらん「の」このむね
- [x] Aria78小节的蛋总みらい「は」
- [x] 86小节くれ「た」
- [x] Aria91小节ひかり「を」

mdzz，居然还没完。

**Comment by Risouw** [comment]
- [x] 君光：第10小节よる改成よあ
- [x] 副歌部分第一句改成こんなにかなしいけしきを（tkpl
- [x] 从57小节开始Harmony改为与keiko八度和声
- [x] 56小节Harmony与Keiko歌词没打
- [ ] 君光钢伴谱子
- [x] ARIA:39小节wa子有一个高音和声
- [x] 24小节二爷歌词没打
